site_name: My Docs
# theme: 
#   name: material
nav:
  - Home: index.md
  - About: about.md
  - Contact: contact.md
  - Getting-started:  getting-started.md
# theme: readthedocs
plugins: 
  - search
  - mkdocs-with-confluence:
      host_url: https://atlas-test-01.atlassian.net/wiki
      space: SOFTWARE
      parent_page_name: Atals-demo
      username: sumitkumar@jmangroup.com
      enabled_if_env: MKDOCS_TO_CONFLUENCE
