name: Publish to Confluence

on:
    push:
        branches:
            - main

permissions:
  contents: write 

jobs:
    publish:
        runs-on: ubuntu-latest

        env:
            MKDOCS_TO_CONFLUENCE: '1'
            CONFLUENCE_USERNAME: ${{secrets.CONFLUENCE_USERNAME}}
            CONFLUENCE_API_TOKEN: ${{secrets.CONFLUENCE_API_TOKEN}}
        
        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.x'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install mkdocs mkdocs-with-confluence
        - name: Deploy to Confluence
          run: mkdocs build
