name: Publish to Confluence

on:
    push:
        branches:
            - main
jobs:
    publish:
        runs-on: ubuntu-latest

        env:
            MKDOCS_TO_CONFLUENCE: '1'
            CONFLUENCE_USERNAME: ${{secrets.CONFLUENCE_USERNAME}}
            CONFLUENCE_API_TOKEN: ${{secrets.CONFLUENCE_API_TOKEN}}
        
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                python-version: '3.x'
            - run: |
                pip install mkdocs mkdocs-with-confluence
                mkdocs build
